In [3]:
import numpy as np
import time

In [4]:
arr=np.array([1,2,3,5,6])

print(arr, type(arr))

[1 2 3 5 6] <class 'numpy.ndarray'>


In [6]:
# execution performance

size=10_000_000

py_list=list(range(size))

start_time=time.time()
#calculate square
sq=[i*i for i in py_list]
end_time=time.time()

print(f"time taken by py_list: {end_time-start_time} seconds")


np_arr= np.array(py_list)
start_time=time.time()

# calculate square
sq1=np_arr**2
end_time=time.time()

print(f"time taken by np_array: {end_time-start_time} seconds")

time taken by py_list: 2.00494384765625 seconds
time taken by np_array: 0.04242086410522461 seconds


In [12]:
# memory
import sys

print(f"size of python list in memory: {sys.getsizeof(py_list)*len(py_list)} bytes")

print(f"size of np array in memory: {np_arr.nbytes} bytes")

size of python list in memory: 800000560000000 bytes
size of np array in memory: 80000000 bytes


In [15]:
#creating 2D array

arr2D=np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])

print(arr2D, arr2D.shape, arr2D.dtype, type(arr2D))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] (4, 3) int64 <class 'numpy.ndarray'>


In [32]:
# create numpy array with using array list

arr1=np.zeros((2,3), dtype="int64")            #prefill with zeros
print(arr1, arr1.shape, arr1.dtype)


arr2=np.ones((3,3))                            #prefill with ones
print(arr2, arr2.shape)


arr3=np.full((3,4), 100)                       #prefill with particular value
print(arr3, arr3.shape)


arr4=np.eye(3)                                 #creates an identity metrix
print(arr4, arr4.shape)


arr5=np.arange(6).reshape(2,3)                 #similar as range in python
print(arr5, arr5.shape)


arr6=np.linspace(1, 100, 4)
print(arr6, arr6.shape)

[[0 0 0]
 [0 0 0]] (2, 3) int64
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] (3, 3)
[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]] (3, 4)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] (3, 3)
[[0 1 2]
 [3 4 5]] (2, 3)
[  1.  34.  67. 100.] (4,)


In [33]:
#properties
arr=np.array([[1,2,3,4], [5,6,7,8]])

print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.ndim)

(2, 4)
8
int64
2


In [34]:
#type casting
#when we already have an existing array
arr=np.array([[1,2,3], [4,5,6], [7,8,9]])

#int64 to float64
float_arr=arr.astype(np.float64)
print(float_arr, float_arr.dtype)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] float64


In [36]:
#reshaping

arr=np.array([[1,2,3], [4,5,6]])
print(arr, arr.shape)

reshaped=arr.reshape((3,2))
print(reshaped, reshaped.shape)

#flatten

flattened=arr.flatten()
print(flattened, flattened.shape)

[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 2 3 4 5 6] (6,)


In [43]:
#indexing
#on 1D array

arr=np.array([1,2,3,4,5])

print(arr[0])
print(arr[4])

#on 2D array

arr2=np.array([[1,2,3], [4,5,6]])

print(arr2[1][1])
print(arr2[1][2])


#fancy indexing
#1D

arr3=np.array([1,2,3,4,5])
idx=[2,4,1]

print(arr3[idx])

#2D
arr4=np.array([[1,2,3], [4,5,6]])
rows=[1,1]
columns=[1,2]

print(arr4[rows, columns])


#boolean indexing
arr5=np.array([1,2,3,4,5,6])

print(arr5[arr5>3])
print(arr5[arr5%2==0])

1
5
5
6
[3 5 2]
[5 6]
[4 5 6]
[2 4 6]


In [45]:
# slicing

arr=np.array([1,2,3,4,5,6])

print(arr[1:3])
print(arr[:])
print(arr[::2])

[2 3]
[1 2 3 4 5 6]
[1 3 5]


In [52]:
#copy vs view in slice
#in py_list
nums=[1,2,3,4,5,6]

sub_list=nums[2:5]
print(sub_list)

sub_list[1]=200

print(sub_list)
print(nums)


#in ndarray

arr=np.array(nums)

sub_arr=arr[2:5]
print(sub_arr)

sub_arr[1]=200

print(sub_arr)
print(arr)

[3, 4, 5]
[3, 200, 5]
[1, 2, 3, 4, 5, 6]
[3 4 5]
[  3 200   5]
[  1   2   3 200   5   6]


In [53]:
#complex numbers

arr1=np.array([3+ 5j])
arr2=np.array([5+8j])

arr=arr1+arr2

print(arr, arr.dtype)

[8.+13.j] complex128


In [56]:
#object datatype

arr=np.array(["prime", 4.15, 2, True])

print(arr, arr.dtype)

['prime' '4.15' '2' 'True'] <U32


In [61]:
#multi dimensional arrays

#2D array
arr2D=np.array([[1,2,3], [4,5,6], [7,8,9]])

print(np.sum(arr2D))

#calculate sum of columns

print(np.sum(arr2D, axis=0))

#calculate sum of rows

print(np.sum(arr2D, axis=1))

#slicing in 2D arrays
print(arr2D[0:2, 1:2])
print(arr2D[1:3, 1:3])

45
[12 15 18]
[ 6 15 24]
[[2]
 [5]]
[[5 6]
 [8 9]]


In [67]:
#3D array

arr3D=np.array([[[1,2],[3,4], [5,6]], [[7,8],[9,10], [11, 12]]])

print(arr3D, arr3D.shape)

#access 4 from this 3D array
print(arr3D[0, 1, 1])

#first row from both layers
print(arr3D[:,:,:1])

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]] (2, 3, 2)
4
[[[ 1]
  [ 3]
  [ 5]]

 [[ 7]
  [ 9]
  [11]]]


In [69]:
#vectorization

arr=np.array([1,2,3,4,5])

#print squares
print(arr **2)

#add 2 in every element in given array
print(arr+2)

[ 1  4  9 16 25]
[3 4 5 6 7]


In [70]:
#broadcasting

arr1=np.array([1,2,3,4,5])
arr2=np.array([[1,2,3,4,5], [6,7,8,9,10]])

print(arr1+arr2)
print(arr1.shape)
print(arr2.shape)

[[ 2  4  6  8 10]
 [ 7  9 11 13 15]]
(5,)
(2, 5)


In [73]:
#standard normalization

arr=np.array([[1,2], [3,4]])

mean=np.mean(arr)
std_dev=np.std(arr)

normalized=(arr-mean)/std_dev
print(normalized)

[[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]


In [77]:
#important function
#aggregate

arr=np.array([1,2,3,4,5])

print(np.sum(arr))
print(np.prod(arr))
print(np.min(arr))
print(np.max(arr))
print(np.argmin(arr))
print(np.argmax(arr))
print(np.median(arr))
print(np.var(arr))

15
120
1
5
0
4
3.0
2.0


In [82]:
#power function

arr=np.array([1,2,3,4,5])

print(np.square(arr))
print(np.sqrt(arr))
print(np.power(arr,3))

[ 1  4  9 16 25]
[1.         1.41421356 1.73205081 2.         2.23606798]
[  1   8  27  64 125]


In [87]:
#log functions

arr=np.array([1,2,3,4,5])

print(np.log(arr))
print(np.log10(arr))
print(np.log2(arr))
print(np.exp(arr))

[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[0.         0.30103    0.47712125 0.60205999 0.69897   ]
[0.         1.         1.5849625  2.         2.32192809]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


In [96]:
#rounding

print(np.round(3.14))
print(np.ceil(3.14))
print(np.floor(3.94))
print(np.trunc(4.57))

arr=np.array([1,2,3,4,3])

print(np.unique(arr))

arr2=np.array([-1.-2,4,5,3])
print(np.abs(arr2))

3.0
4.0
3.0
4.0
[1 2 3 4]
[3. 4. 5. 3.]
