# Practice numpy

In [1]:
import numpy as np

# LEVEL-1

1. Import NumPy and create a 1D array containing:

In [7]:
arr=np.array([10, 20, 30, 40, 50])
print(arr.dtype)
print(arr.ndim)
print(arr.shape)
print(arr.size)

int64
1
(5,)
5


2. Create a NumPy array containing numbers from 1 to 20.

In [8]:
my_list=[]
for i in range(21):
    my_list.append(i)

arr=np.array(my_list)
arr
    

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

3. Create an array of 10 zeros.

In [12]:
arr=np.zeros(10)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

4. Create an array of 5 ones.

In [13]:
arr=np.ones(5)
arr

array([1., 1., 1., 1., 1.])

5. Create an array containing even numbers from 2 to 20.

In [14]:
my_list=[]

for i in range(2,21,2):
    my_list.append(i)

arr=np.array(my_list)
arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

6. Create an array containing:

In [16]:
arr=np.arange(0, 51, 5)
arr

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

7. Create a 3×3 matrix:

In [18]:
arr=np.arange(1,10).reshape(3,3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# LEVEL-2

8. Given:

arr = np.array([10, 20, 30, 40, 50, 60])

Find:

first element,
last element,
third element,
elements from index 1 to 4,
last 3 elements,
every second element

In [27]:
arr = np.array([10, 20, 30, 40, 50, 60])

print("first element:", arr[0])
print("last element:", arr[len(arr)-1])
print("third element:", arr[2])
print("elements from index 1 to 4", arr[1:5])
print("last 3 elements", arr[3:])
print("every second elements", arr[::2])

first element: 10
last element: 60
third element: 30
elements from index 1 to 4 [20 30 40 50]
last 3 elements [40 50 60]
every second elements [10 30 50]


9. Given:

arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])

Find:

50,
90,
entire second row,
entire third column,
first two rows,
last two columns

In [ ]:
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])


10. Create a 4×5 array containing numbers from 1 to 20 and extract:
    7  8
    12 13

In [11]:
array=np.arange(1,21).reshape(4,5)

print(array[1:3, 1:3])

[[ 7  8]
 [12 13]]


In [7]:
array

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

# LEVEL-3

11. Given:
marks = np.array([65, 72, 88, 90, 56, 79, 95])

Find:

total marks
average
maximum
minimum
standard deviation

In [15]:
marks=np.array([65, 72, 88, 90, 56, 79, 95])

print("total_marks:", np.sum(marks))
print("average marks:", np.mean(marks))
print("maximum marks:", np.max(marks))
print("minimum marks:", np.min(marks))
print("standard deviation:", np.std(marks))

total_marks: 545
average marks: 77.85714285714286
maximum marks: 95
minimum marks: 56
standard deviation: 13.217181149966146


12. Add 5 bonus marks to every student's marks.

In [16]:
bonus_marks=np.array([65, 72, 88, 90, 56, 79, 95]) +5

bonus_marks

array([ 70,  77,  93,  95,  61,  84, 100])

13. Given:
prices = np.array([100, 200, 300, 400])

Increase every price by 10%.

In [19]:
prices = np.array([100, 200, 300, 400])

increase_price=prices+prices*10/100

increase_price


array([110., 220., 330., 440.])

14. Given:
temperatures = np.array([20, 25, 30, 35, 40])

Convert all temperatures from Celsius to Fahrenheit.

Formula:

F = C × 9/5 + 32

In [20]:
temperatures = np.array([20, 25, 30, 35, 40])

feherneit_temperature= temperatures*9/5+32

feherneit_temperature

array([ 68.,  77.,  86.,  95., 104.])

# LEVEL-4

15. Given:
scores = np.array([45, 78, 92, 33, 67, 88, 29, 95])

Find all scores greater than 70.

In [22]:
scores = np.array([45, 78, 92, 33, 67, 88, 29, 95])

print(scores[scores> 70])



[78 92 88 95]


16. Find all scores less than 50.

In [23]:
print(scores[scores< 50])

[45 33 29]


17. Find all scores between 60 and 90.

In [26]:
print(scores[(scores> 60) & (scores < 90)])

[78 67 88]


18. Replace every score below 50 with 50.

In [28]:
scores[scores< 50]=50

scores

array([50, 78, 92, 50, 67, 88, 50, 95])

19. Given:
ages = np.array([15, 22, 18, 30, 12, 25, 17, 40])

Find people who are 18 or older

In [29]:
ages = np.array([15, 22, 18, 30, 12, 25, 17, 40])

print(ages[ages>=18])

[22 18 30 25 40]


# LEVEL-5

20. Create numbers from 1 to 12 and reshape them into:
1   2   3   4
5   6   7   8
9  10  11  12

In [30]:
arr=np.arange(1,13).reshape(3,4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

21. Reshape numbers 1–12 into a 2×6 array.

In [31]:
reshaped_arr=arr.reshape(2,6)

reshaped_arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

22. Given:
arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])

Find the sum:

of all elements
of each row
of each column

In [33]:
arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])

print("sum of all elements:", np.sum(arr))
print("sum of each row:", np.sum(arr, axis=1))
print("sum of each column:", np.sum(arr, axis=0))

sum of all elements: 450
sum of each row: [ 60 150 240]
sum of each column: [120 150 180]


23. Find the average of each row and each column.

Hint: This is where axis=0 and axis=1 become important.

In [35]:
print("average of each row:", np.mean(arr, axis=1))
print("average of each column:", np.mean(arr, axis=0))

average of each row: [20. 50. 80.]
average of each column: [40. 50. 60.]


# LEVEL-6

24. Create:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

Combine them into:

[1 2 3 4 5 6]

In [38]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

sum=a+b
sum

array([5, 7, 9])

25. Combine them vertically into:
1 2 3
4 5 6

In [2]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])

result=np.array([arr1, arr2])
result

array([[1, 2, 3],
       [4, 5, 6]])

26. Split the following array into 3 equal parts:
arr = np.array([10, 20, 30, 40, 50, 60])

In [5]:
arr = np.array([10, 20, 30, 40, 50, 60])

result=np.split(arr,3)
result


[array([10, 20]), array([30, 40]), array([50, 60])]

27. You have marks of 5 students in 3 subjects:
marks = np.array([
    [80, 75, 90],
    [60, 65, 70],
    [95, 90, 85],
    [50, 55, 60],
    [88, 92, 90]
])

Find:

average marks of each student
average marks of each subject
highest mark
lowest mark
student(s) whose average is above 80

In [15]:
marks = np.array([
    [80, 75, 90],
    [60, 65, 70],
    [95, 90, 85],
    [50, 55, 60],
    [88, 92, 90]
])

print("average marks of each student:", np.mean(marks, axis=1) )
print("average marks of each subject:", np.mean(marks, axis=0) )
print("highest marks:", np.max(marks) )
print("lowest marks:", np.min(marks) )
average_marks=np.mean(marks, axis=1)
print("marks above 80:", (marks[average_marks > 80]))

average marks of each student: [81.66666667 65.         90.         55.         90.        ]
average marks of each subject: [74.6 75.4 79. ]
highest marks: 95
lowest marks: 50
marks above 80: [[80 75 90]
 [95 90 85]
 [88 92 90]]
