# Practice numpy

In [1]:
import numpy as np

# LEVEL-1

1. Import NumPy and create a 1D array containing:

In [7]:
arr=np.array([10, 20, 30, 40, 50])
print(arr.dtype)
print(arr.ndim)
print(arr.shape)
print(arr.size)

int64
1
(5,)
5


2. Create a NumPy array containing numbers from 1 to 20.

In [8]:
my_list=[]
for i in range(21):
    my_list.append(i)

arr=np.array(my_list)
arr
    

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

3. Create an array of 10 zeros.

In [12]:
arr=np.zeros(10)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

4. Create an array of 5 ones.

In [13]:
arr=np.ones(5)
arr

array([1., 1., 1., 1., 1.])

5. Create an array containing even numbers from 2 to 20.

In [14]:
my_list=[]

for i in range(2,21,2):
    my_list.append(i)

arr=np.array(my_list)
arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

6. Create an array containing:

In [16]:
arr=np.arange(0, 51, 5)
arr

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

7. Create a 3×3 matrix:

In [18]:
arr=np.arange(1,10).reshape(3,3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# LEVEL-2

8. Given:

arr = np.array([10, 20, 30, 40, 50, 60])

Find:

first element,
last element,
third element,
elements from index 1 to 4,
last 3 elements,
every second element

In [27]:
arr = np.array([10, 20, 30, 40, 50, 60])

print("first element:", arr[0])
print("last element:", arr[len(arr)-1])
print("third element:", arr[2])
print("elements from index 1 to 4", arr[1:5])
print("last 3 elements", arr[3:])
print("every second elements", arr[::2])

first element: 10
last element: 60
third element: 30
elements from index 1 to 4 [20 30 40 50]
last 3 elements [40 50 60]
every second elements [10 30 50]


9. Given:

arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])

Find:

50,
90,
entire second row,
entire third column,
first two rows,
last two columns

In [ ]:
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
